# Site settings
title: Stan Kondrat
email: stan.kondrat аt gmail dоt com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stan-kondrat.github.io/" # the base hostname & protocol for your site
github_username:  stan-kondrat
name: "Stanislav Kondratyuk"
title_separator: "-"
subtitle: "Personal Website"
description: ""
locale: "en-US"
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "UTC" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Stan Kondrat"
  avatar: "/assets/bio-photo.jpg"
  bio: "Software Engineer"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://stan-kondrat.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stan-kondrat"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stankondrat"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://stan-kondrat.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/stan-kondrat"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/stankondrat"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
